project:
  type: website

website:
  title: "FRE 474 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - syllabus.qmd
      - causalinftopics.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

