---
title: "Course Schedule"
output: html_document
---

+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Number** | **Day** | **Date**  | **Topic**                                         | **Assignments/Quizzes/Reflections.**                                                                            | **Additional Information**                                                                                                                                                                                                                                                         |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 1  | T       | 1/9/2024  | Introduction, and the Economics of Conservation   |                                                                                                                 | Papers to read:                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   |                                                                                                                 | 1\) Metrick, A., & Weitzman, M. L. (1998). Conflicts and choices in biodiversity preservation. Journal of Economic Perspectives, 12(3), 21-34, and                                                                                                                                 |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   |                                                                                                                 | 2\) Adamowicz, W. L. (2016). Economic analysis and species at risk: Lessons learned and future challenges. Canadian Journal of Agricultural Economics/Revue canadienne d'agroeconomie, 64(1), 21-32.                                                                               |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   |                                                                                                                 | Videos to Watch: Nick Huntington-Klien on interpreting regression coefficients:                                                                                                                                                                                                    |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   |                                                                                                                 | 1\) https://youtu.be/3WuHicIVxnM,                                                                                                                                                                                                                                                  |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   |                                                                                                                 | 2\) https://youtu.be/J8IHdu-oM64.                                                                                                                                                                                                                                                  |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 1      | W       | 1/10/2024 | No lab                                            |                                                                                                                 | See Lecture 1                                                                                                                                                                                                                                                                      |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 2  | Th      | 1/11/2024 | The economics of Conservation Continued           | Assignment 1 given (covers Random Assignment, and Regression Analysis).                                         | See Lecture 1                                                                                                                                                                                                                                                                      |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 3  | T       | 1/16/2024 | Counterfactual Thinking                           |                                                                                                                 | Paper to Read: Ferraro, P. J. (2009). Counterfactual thinking and impact evaluation in environmental policy. New directions for evaluation, 2009(122), 75-84.                                                                                                                      |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 2      | W       | 1/17/2024 | No lab                                            |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 4  | Th      | 1/18/2024 | Counterfactual Thinking                           | Reflection 1 due midnight Jan 21st.                                                                             | Paper to Read: Ferraro, P. J. (2009). Counterfactual thinking and impact evaluation in environmental policy. New directions for evaluation, 2009(122), 75-84.                                                                                                                      |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 5  | T       | 1/23/2024 | The Economics of Forest Conservation              |                                                                                                                 | Paper to read: Foster, A.D. and Rosenzweig, M.R., 2003. Economic growth and the rise of forests. The Quarterly Journal of Economics, 118(2), pp.601-637.                                                                                                                           |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 3      | W       | 1/24/2024 | No lab                                            |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 6  | Th      | 1/25/2024 | Random Assignment                                 |                                                                                                                 | Chapter 1, Angrist and Pischke                                                                                                                                                                                                                                                     |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 7  | T       | 1/30/2024 | The Economics of Forest Conservation              | Assignment 2 given (Covers DAGs and Instrumental Variables)                                                     | Paper to read: Foster, A.D. and Rosenzweig, M.R., 2003. Economic growth and the rise of forests. The Quarterly Journal of Economics, 118(2), pp.601-637.                                                                                                                           |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 4      | W       | 1/31/2024 | Lab on Random Assignment                          |                                                                                                                 | Chapter 1, Angrist and Pischke                                                                                                                                                                                                                                                     |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 8  | Th      | 2/1/2024  | DAGs                                              | Reflection 2 due midnight Feb 4th                                                                               | Chapter 6, 7, The Effect Book: <https://theeffectbook.net/index.html>, Chapter 3, Causal Inference: The Mixtape, <https://mixtape.scunning.com/dag.html.>                                                                                                                          |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   | Assignment 1 due midnight Feb 5th                                                                               |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 9  | T       | 2/6/2024  | Economic Development, Species Loss and Extraction |                                                                                                                 | Paper to read: Naidoo, R., & Adamowicz, W. L. (2001). Effects of economic prosperity on numbers of threatened species. Conservation Biology, 15(4), 1021-1029.                                                                                                                     |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 5      | W       | 2/7/2024  | Lab on DAGs/Regression Analysis                   |                                                                                                                 | Chapter 2, Angrist and Pischke                                                                                                                                                                                                                                                     |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 10 | Th      | 2/8/2024  | Regression Analysis                               |                                                                                                                 | Chapter 2, Angrist and Pischke                                                                                                                                                                                                                                                     |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 11 | T       | 2/13/2024 | Ecosystem Services and Land Rental Markets        |                                                                                                                 | Paper to Read: Manning, D. T., & Ando, A. (2022). Ecosystem Services and Land Rental Markets: Producer Costs of Bat Population Crashes. Journal of the Association of Environmental and Resource Economists, 9(6), 1235-1277.                                                      |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 6      | W       | 2/14/2024 | Lab on Regression Analysis/Fixed Effects.         |                                                                                                                 | Read: The Effect, [Chapter 16](https://theeffectbook.net/ch-FixedEffects.html)                                                                                                                                                                                                     |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 12 | Th      | 2/15/2024 | Instrumental Variables                            | Quiz 1 (45 minutes in class. Covers Random Assignment, Regression Analysis, DAG's, and Instrumental Variables). | Chapter 3, Angrist and Pischke                                                                                                                                                                                                                                                     |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   | Reflection 3 due midnight Feb 18th.                                                                             |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   | Assignment 2 due midnight Feb 17th.                                                                             |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|            |         | 2/20/2024 | Midsemester Break                                 |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|            |         | 2/21/2024 | Midsemester Break                                 |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|            |         | 2/22/2024 | Midsemester Break                                 |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 13 | T       | 2/27/2024 | Ecosystem Services and Land Rental Markets        | Assignment 3 given (covers regression discontinuity, and difference and differences).                           | Paper to Read: Manning, D. T., & Ando, A. (2022). Ecosystem Services and Land Rental Markets: Producer Costs of Bat Population Crashes. Journal of the Association of Environmental and Resource Economists, 9(6), 1235-1277.                                                      |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 7      | W       | 2/28/2024 | Lab on Instrumental Variables                     |                                                                                                                 | Chapter 3, Angrist and Pischke                                                                                                                                                                                                                                                     |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 14 | Th      | 2/29/2024 | Regression Discontinuity, lecture.                |                                                                                                                 | Chapter 4, Angrist and Pischke.                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 15 | T       | 3/5/2024  | Farm size and biodiversity.                       |                                                                                                                 | Paper to read: Noack, F., Larsen, A., Kamp, J., & Levers, C. (2021). A bird's eye view of farm size and biodiversity: The ecological legacy of the iron curtain. American Journal of Agricultural Economics.                                                                       |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 8      | W       | 3/6/2024  | Lab on Regression Discontinuity                   |                                                                                                                 | Chapter 4, Angrist and Pischke.                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 16 | Th      | 3/7/2024  | Differences in Differences.                       | Reflection 4 due midnight March 12th.                                                                           | Chapter 5, Angrist and Pischke.                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 17 | T       | 3/12/2024 | Conservation and its impact on labor markets.     | Assignment 4 given (designed to help you start your final projects).                                            | Paper to read: Frank, E., (2020), The Impact of the Northern Spotted Owl Conservation Plan on Local Labor Markets, working paper.                                                                                                                                                  |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 9      | W       | 3/13/2024 | Lab on Differences in Differences.                |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 18 | Th      | 3/14/2024 | Topical Discussion.                               | Assignment 3 due midnight March 15th.                                                                           | Topic to be determined.                                                                                                                                                                                                                                                            |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 19 | T       | 3/19/2024 | Protected Areas                                   |                                                                                                                 | Paper to read: Andam, Kwaw S, Paul J Ferraro, Katharine R E Sims, Andrew Healy, and Margaret B Holland. 2010. "Protected areas reduced poverty in Costa Rica and Thailand." Proceedings of the National Academy of Sciences of the United States of America 107 (22): 9996--10001. |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 10     | W       | 3/20/2024 | No lab this week                                  | Start work on your final papers, includin Assignments 4 and 5                                                   |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 20 | Th      | 3/21/2024 | Discussion on your final projects.                | Assignment 5 given (also designed to help you complete tasks related to the final project).                     | Will address issues related to your final projects.                                                                                                                                                                                                                                |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   | Assignment 4 due midnight March 22nd.                                                                           |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   | Reflection 5 due midnight March 24th.                                                                           |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 21 | T       | 3/26/2024 | Protected Areas                                   |                                                                                                                 | Paper to read: Burgess, R., Costa, F. J., & Olken, B. A. (2018). Wilderness Conservation and the Reach of the State: Evidence from National Borders in the Amazon (No. w24861). National Bureau of Economic Research                                                               |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 11     | W       | 3/27/2024 | Data lab.                                         | Quiz 2 (coding exercise in class).                                                                              |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 22 | Th      | 3/28/2024 | Reintroduction and Local Economies.               | Referee report assigned.                                                                                        | Paper to read: Li, L., & Ando, A. W. (2022). The impact of bison reintroduction on local economies. Agricultural and Resource Economics Review, 51(3), 455-472.                                                                                                                    |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   | Assignment 5 due midnight Mar 29.                                                                               |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 23 | T       | 4/2/2024  | Reintroduction and Local Economies.               |                                                                                                                 | Paper to read: Li, L., & Ando, A. W. (2022). The impact of bison reintroduction on local economies. Agricultural and Resource Economics Review, 51(3), 455-472.                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 12     | W       | 4/3/2024  | Data lab.                                         |                                                                                                                 | Will address issues related to your final projects.                                                                                                                                                                                                                                |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 24 | Th      | 4/4/2024  | Endangered Species Act: Matching Methods          | Reflection 6 due midnight April 7th.                                                                            | Reading Assigned: Ferraro, P. J., McIntosh, C., & Ospina, M. (2007). The effectiveness of the US endangered\                                                                                                                                                                       |
|            |         |           |                                                   |                                                                                                                 | species act: An econometric analysis using matching methods. Journal of Environmental\                                                                                                                                                                                             |
|            |         |           |                                                   |                                                                                                                 | Economics and Management, 54(3), 245-261.                                                                                                                                                                                                                                          |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 25 | T       | 4/9/2024  | Topical Discussion.                               |                                                                                                                 | Topic to be determined (topical discussion).                                                                                                                                                                                                                                       |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lab 13     | W       | 4/10/2024 | Data lab.                                         |                                                                                                                 | Will address issues related to your final projects.                                                                                                                                                                                                                                |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture 26 | Th      | 4/11/2024 | Endangered Species Act and Wrap Up.               | Quiz 3 (covers Fixed Effects, Regression Discontinuity, Differences and Differences).                           | Reading Assigned: Ferraro, P. J., McIntosh, C., & Ospina, M. (2007). The effectiveness of the US endangered\                                                                                                                                                                       |
|            |         |           |                                                   |                                                                                                                 | species act: An econometric analysis using matching methods. Journal of Environmental\                                                                                                                                                                                             |
|            |         |           |                                                   | Referee report due midnight April 19th.                                                                         | Economics and Management, 54(3), 245-261.                                                                                                                                                                                                                                          |
|            |         |           |                                                   |                                                                                                                 |                                                                                                                                                                                                                                                                                    |
|            |         |           |                                                   | Final Paper due midnight Apr 26th.                                                                              |                                                                                                                                                                                                                                                                                    |
+------------+---------+-----------+---------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
