---
title: "Course Schedule"
output: html_document
---

The below schedule is from 2023. It will be updated soon for 2024.

+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date   | Topic                                             | Assignments/Quizzes/Reflections                                                                                                                                      | Readings/Videos                                                                                                                                                                                  |
+========+===================================================+======================================================================================================================================================================+==================================================================================================================================================================================================+
| Jan 10 | Introduction and the Economics of Conservation    |                                                                                                                                                                      | Papers to read: 1) [Metrick, A., & Weitzman, M. L. (1998)](https://www.aeaweb.org/articles?id=10.1257/jep.12.3.21), 2) [Adamowicz, W. L. (2016)](https://doi.org/10.1111/cjag.12098)             |
|        |                                                   |                                                                                                                                                                      |                                                                                                                                                                                                  |
|        |                                                   |                                                                                                                                                                      | Videos to Watch: Nick Huntington-Klien on interpreting regression coefficient, [video 1](https://www.youtube.com/watch?v=3WuHicIVxnM) and [video 2](https://www.youtube.com/watch?v=J8IHdu-oM64) |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Jan 12 | The Economics of Conservation                     | Assignment 1 given (covers Random Assignment, and Regression Analysis)                                                                                               | same as Jan 10 class                                                                                                                                                                             |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Jan 17 | Counterfactual Thinking                           |                                                                                                                                                                      | Paper to read: [Ferraro, P.J. (2009)](https://doi.org/10.1002/ev.297)                                                                                                                            |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Jan 19 | Random Assignment, lecture and lab                | Reflection 1 due midnight Jan 22nd                                                                                                                                   | Read: Chapter 1, Angrist and Pischke                                                                                                                                                             |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Jan 24 | The Economics of Forest Conservation              |                                                                                                                                                                      | Paper to read: [Foster, A.D, and Rosenzweig, M.R. (2003)](https://doi.org/10.1162/003355303321675464)                                                                                            |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Jan 26 | Regression Analysis, lecture and lab              |                                                                                                                                                                      | Read: Chapter 2, Angrist and Pischke                                                                                                                                                             |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Jan 31 | The Economics of Forest Conservation              | Assignment 1 due, Assignment 2 given (Covers DAGs and Instrumental Variables)                                                                                        | Paper to read: [Foster, A.D, and Rosenzweig, M.R. (2003)](https://doi.org/10.1162/003355303321675464) (same as Jan 24 class)                                                                     |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Feb 2  | Directed Acyclic Graphs                           | Reflection 2 due midnight Feb 5th                                                                                                                                    | Read: Chapters 6 and 7 of [The Effect](https://theeffectbook.net/index.html), Chapter 3 of [Causal Inference: The Mixtape](https://mixtape.scunning.com/)                                        |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Feb 7  | Economic Development, Species Loss and Extraction |                                                                                                                                                                      | Paper to read: [Naidoo, R., & Adamowicz, W. L. (2001)](https://doi.org/10.1046/j.1523-1739.2001.0150041021.x)                                                                                    |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Feb 9  | Instrumental Variables                            |                                                                                                                                                                      | Read: Chapter 3, Angrist and Pischke                                                                                                                                                             |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Feb 14 | Economic Development, Species Loss and Extraction |                                                                                                                                                                      | Paper to read: [Eisenbarth, S. (2022)](https://doi.org/10.1016/j.jeem.2021.102603)                                                                                                               |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Feb 16 | Fixed Effects lab                                 | Quiz 1 (45 minutes in class, covers Random Assignment, Regression Analysis, DAG's, and Instrumental Variables), Assignment 2 due, Reflection 3 due midnight Feb 19th | Read: The Effect, [Chapter 16](https://theeffectbook.net/ch-FixedEffects.html)                                                                                                                   |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Feb 21 | Midterm Break                                     |                                                                                                                                                                      |                                                                                                                                                                                                  |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Feb 23 | Midterm Break                                     |                                                                                                                                                                      |                                                                                                                                                                                                  |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Feb 28 | Ecosystem Services and Land Rental Markets        | Assignment 3 given (Covers Regression Discontinuity, and Difference-in-Differences)                                                                                  | Paper to read: [Manning, D.T., and Ando, A. (2022)](https://www.journals.uchicago.edu/doi/10.1086/720303)                                                                                        |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mar 2  | Regression Discontinuity, lecture and lab         |                                                                                                                                                                      | Read: Chapter 4, Angrist and Pischke                                                                                                                                                             |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mar 7  | Farm Size and Biodiversity                        |                                                                                                                                                                      | Paper to read: [Noack, F. et al. (2021)](https://doi.org/10.1111/ajae.12274)                                                                                                                     |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mar 9  | Differences in Differences, lecture and lab       | Reflection 4 due midnight March 12th                                                                                                                                 | Read: Chapter 5, Angrist and Pischke                                                                                                                                                             |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mar 14 | Conservation and its impact on labor markets      | Assignment 3 due, Assignment 4 given (designed to help you start your final projects)                                                                                | Paper to read: [Frank, E. (2020)](https://www.eyalfrank.com/wp-content/uploads/2020/02/Frank_NSO_Logging_Jobs.pdf)                                                                               |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mar 16 | Topical Discussion                                | Quiz 2 (in-class coding exercise)                                                                                                                                    | Paper to be determined (related to topical discussion)                                                                                                                                           |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mar 21 | Protected Areas                                   |                                                                                                                                                                      | Paper to read: [Andam, K.S., Ferraro, P.J., and Sims, K.R.E. (2010)](https://doi.org/10.1073/pnas.0914177107)                                                                                    |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mar 23 | Data Lab                                          | Assignment 4 due, Assignment 5 given (also designed to help you complete tasks related to the final project), Reflection 5 due midnight March 26th                   | We will address issues related to your final projects                                                                                                                                            |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mar 28 | Protected Areas                                   |                                                                                                                                                                      | Paper to read: [Burgess, R., Costa, F. J., & Olken, B. A. (2018)](https://www.nber.org/papers/w24861)                                                                                            |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mar 30 | Data lab                                          | Assignment 5 due, Referee report assigned                                                                                                                            | We will address issues related to your final projects                                                                                                                                            |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Apr 4  | Reintroduction and Local Economies                |                                                                                                                                                                      | Paper to read: [Li, L., & Ando, A. W. (2022)](https://doi.org/10.1017/age.2022.13)                                                                                                               |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Apr 6  | Endangered Species Act: Matching Methods          | Reflection 6 due midnight April 9th                                                                                                                                  | Paper to read: [Ferraro, P. J., McIntosh, C., & Ospina, M. (2007)](https://doi.org/10.1016/j.jeem.2007.01.002)                                                                                   |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Apr 11 | Topical Discussion                                |                                                                                                                                                                      | Paper to be determined (related to topical discussion)                                                                                                                                           |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Apr 13 | Wrap up                                           | Quiz 3 (covers Fixed Effects, Regression Discontinuity, Differences and Differences), Referee report due midnight April 21th, Final paper due midnight April 28th    |                                                                                                                                                                                                  |
+--------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
